---
install_csf: false

csf_testing: 0
csf_tcp_in: 20,21,22,23,25,53,80,110,143,443,465,587,953,993,995,1311,2078,2080,2083,2087,2096,3306,3690,12000:13000,30000:50000
csf_tcp_out: 20,21,22,25,37,43,53,80,110,113,443,465,587,873,953,995,2082,2083,2086,2087,2089,2195,2703,3306,3690,4445,6000:9000,12000:13000,27000:27100
csf_udp_in: 20,21,53,953,5000:9999
csf_udp_out: 20,21,53,113,123,873,953,6277,5000:9999,27000:27100
csf_ipv6_enabled: 1
csf_tcp6_in: 20,21,22,23,25,53,80,110,143,443,465,587,953,993,995,1311,2078,2080,2083,2087,2096,3306,3690,12000:13000,30000:50000
csf_tcp6_out: 0:65535
csf_udp6_in: 20,21,53,953,5000:9999
csf_udp6_out: 0:65535
csf_allow_icmp_in: 1
csf_allow_icmp_out: 1
csf_eth_device: "{{ ansible_default_ipv4.interface }}"
csf_eth6_device: "{% if ansible_default_ipv6.interface is defined %} {{ ansible_default_ipv6.interface }} {% endif %}"
csf_eth_device_skip:
csf_use_conntrack: 1
csf_deny_ip_limit: 1000
csf_deny_temp_ip_limit: 1000
csf_lf_daemon: 1
csf_faststart: 1
csf_smtp_block: 1
csf_smtp_allowlocal: 1
csf_blocked_smtp_ports: 25,587
csf_lf_alert_to: csf@lithiumhosting.net
csf_lf_alert_from: alerts@lithiumhosting.net
csf_safechainupdate: 1

### Login Failure Limits ###
csf_lf_sshd_limit: 20
csf_lf_sshd_perm: 1
csf_lf_ftpd_limit: 20
csf_lf_ftpd_perm: 1
csf_lf_smtpauth_limit: 0
csf_lf_smtpauth_perm: 0
csf_lf_eximsyntax_limit: 10
csf_lf_eximsyntax_perm: 1
csf_lf_pop3d_limit: 0
csf_lf_pop3d_perm: 0
csf_lf_imapd_limit: 0
csf_lf_imapd_perm: 0
csf_lf_htaccess_limit: 20
csf_lf_htaccess_perm: 1
csf_lf_cpanel_limit: 20
csf_lf_cpanel_perm: 1
csf_lf_modsec_limit: 0
csf_lf_modsec_perm: 0
csf_lf_bind_limit: 0
csf_lf_bind_perm: 0
csf_lf_suhosin_limit: 0
csf_lf_suhosin_perm: 0
csf_lf_cxs_limit: 0
csf_lf_cxs_perm: 0
csf_lf_qos_limit: 0
csf_lf_qos_perm: 0
csf_symlink_limit: 0
csf_symlink_perm: 0

csf_lf_ssh_email_alert: 0
csf_lf_su_email_alert: 0
csf_lf_console_email_alert: 0
csf_lf_cpanel_alert: 0
csf_lf_cpanel_alert_users: "root"

### X_ARF Abuse Reports ###
csf_x_arf: 0
csf_x_arf_from: ""
csf_x_arf_to: ""
csf_x_arf_abuse: 0

### Messenger ###
csf_messenger: 0
csf_messenger_html: 8888
csf_messenger_html_in: "80,443,2082,2083,2086,2087,2095,2096"
csf_messenger_text: 8889
csf_messenger_text_in: 21